name: pr_checker

on:
  pull_request:
    types: [opened, reopened, closed, edited]
    
jobs:
  pr_checker:
    name: pr-check
    runs-on: ubuntu-latest
    steps:
      - id: do_some_checks
        run: |
          echo "DOING MY CHECK!"
          exit 0